apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    web: my-php
spec:
  replicas: 3
  selector:
    matchlabels:
      web: my-php
  template:
    metadata:
      labels:
        web: my-php
    spec:
      containers:
      - name: php-container
        image: tharun13055/php:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-php
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    sessionAffinity: none
