version: "3.1"
services:
  mongodb:
    image: mongo:latest
    container_name: mrdevopsmongodb
    restart: always
    ports:
      - 22017:22017
  springboot:
    image: springboot-mongodb:1.0
    container_name: mongodb-springboot
    restart: always
    ports:
      - 8080:8080
    links:
      - mrdevopsmongodb