version: '3.8'
services:
  php_env:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
  db:
    container_name: mysql_container
    image: mysql:latest
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-volume:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password

volumes:
  db-volume: